# Secret environment variables (references to K8s secrets)
envSecrets:
  MONGODB_URI: aircraft-ground-ops
  DATABASE_NAME: aircraft-ground-ops
  AWS_REGION: aircraft-ground-ops
  AWS_PROFILE: aircraft-ground-ops
  COMPLETION_MODEL: aircraft-ground-ops
  EMBEDDING_MODEL: aircraft-ground-ops
  NEXT_PUBLIC_ENV: aircraft-ground-ops

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"
  annotations:
    iam.gke.io/gcp-service-account: "manufacturing-kanopy-sa@manufacturing-project-425012.iam.gserviceaccount.com"

# Mount GCP credential config and service account token
extraVolumes:
 - name: gcp-creds
   configMap:
     name: gcp-wif-config
 - name: gcp-token
   projected:
     sources:
     - serviceAccountToken:
         path: token
         expirationSeconds: 3600
         audience: "//iam.googleapis.com/projects/362614368442/locations/global/workloadIdentityPools/kanopy-manufacturing-wif-pool/providers/kanopy-manufacturing-provider"


extraVolumeMounts:
 - name: gcp-creds
   mountPath: /etc/gcp
   readOnly: true
 - name: gcp-token
   mountPath: /var/run/service-account
   readOnly: true
